---
- hosts: instances
  become: yes
  gather_facts: true
  tasks:
    - name: Apt update & upgrade
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install NGINX
      apt:
        name:
          - nginx
          - git
    - name: Start NGiNX
      service:
        name: nginx
        state: started
    - name: Clone html repo
      git:
        clone: yes
        dest: /var/www/jenkins
        repo: 'https://github.com/Xelzs/jenkins-ansible.git'
    - name: Move only html file to www
      shell: mv /var/www/jenkins/index.html /var/www/html/index.html